FIT5032_VMedProject/Controllers/ClinicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FIT5032_VMedProject.Models;

namespace FIT5032_VMedProject.Controllers
{
    public class ClinicsController : Controller
    {
        private Entities2 db = new Entities2();

        // GET: Clinics
        public ActionResult Index()
        {
            return View(db.Clinics.ToList());
        }

        // GET: Clinics/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clinic clinic = db.Clinics.Find(id);
            if (clinic == null)
            {
                return HttpNotFound();
            }
            return View(clinic);
        }

        // GET: Clinics/Create
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clinics/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create([Bind(Include = "ClinicID,ClinicName,Address,Latitude,Longitude,ContactNumber")] Clinic clinic)
        {
            if (ModelState.IsValid)
            {
                db.Clinics.Add(clinic);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(clinic);
        }

        // GET: Clinics/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clinic clinic = db.Clinics.Find(id);
            if (clinic == null)
            {
                return HttpNotFound();
            }
            return View(clinic);
        }

        // POST: Clinics/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit([Bind(Include = "ClinicID,ClinicName,Address,Latitude,Longitude,ContactNumber")] Clinic clinic)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clinic).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(clinic);
        }

        // GET: Clinics/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clinic clinic = db.Clinics.Find(id);
            if (clinic == null)
            {
                return HttpNotFound();
            }
            return View(clinic);
        }

        // POST: Clinics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteConfirmed(int id)
        {
            Clinic clinic = db.Clinics.Find(id);
            db.Clinics.Remove(clinic);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FIT5032_VMedProject/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FIT5032_VMedProject.Models;

namespace FIT5032_VMedProject.Controllers
{
    public class DoctorsController : Controller
    {
        private Entities2 db = new Entities2();

        // GET: Doctors
        public ActionResult Index()
        {
            var doctors = db.Doctors.Include(d => d.Clinic);
            return View(doctors.ToList());
        }

        // GET: Doctors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // GET: Doctors/DoctorRatings/5
        public ActionResult DoctorRatings(int id)
        {
            // Redirect to the "ViewRatings" action in the "RatingsController"
            return RedirectToAction("ViewRatings", "Ratings", new { doctorId = id });
        }

        // GET: Doctors/Create
        [Authorize(Roles ="Administrator")]
        public ActionResult Create()
        {
            ViewBag.ClinicID = new SelectList(db.Clinics, "ClinicID", "ClinicName");
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create([Bind(Include = "DoctorID,FirstName,LastName,Specialization,ContactNumber,Email,ClinicID,AverageRating")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Doctors.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClinicID = new SelectList(db.Clinics, "ClinicID", "ClinicName", doctor.ClinicID);
            return View(doctor);
        }

        // GET: Doctors/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClinicID = new SelectList(db.Clinics, "ClinicID", "ClinicName", doctor.ClinicID);
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit([Bind(Include = "DoctorID,FirstName,LastName,Specialization,ContactNumber,Email,ClinicID,AverageRating")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClinicID = new SelectList(db.Clinics, "ClinicID", "ClinicName", doctor.ClinicID);
            return View(doctor);
        }

        // GET: Doctors/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctors.Find(id);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FIT5032_VMedProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FIT5032_VMedProject.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FIT5032_VMedProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<style>
    main {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
    }

    h2 {
        font-size: 36px;
        font-weight: bold;
        color: #333;
        text-align: center;
        background-color: #0000A0; /* Dark-blue background color */
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        color: white;
    }

    section {
        margin: 20px 0;
        background-color: #428BCA; /* Light-blue background color for the section */
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    }

    h3 {
        font-size: 28px;
        font-weight: bold;
        color: #333;
        text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.2);
        cursor: pointer;
        position: relative;
    }

        h3::after {
            content: "\25BC";
            font-size: 20px;
            position: absolute;
            right: 0;
            top: 50%;
            transform: translateY(-50%);
            transition: transform 0.3s;
        }

    .dropdown-content {
        display: none;
        padding: 10px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
        margin-top: 10px;
    }

    .show {
        display: block;
    }
</style>

<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title VMed Medical Imaging Group</h2>

    <p>
        At VMed Medical Imaging Group, we are dedicated to advancing healthcare through state-of-the-art MRI (Magnetic Resonance
        Imaging) technology. Our commitment to providing exceptional medical imaging services has made us a trusted partner for
        patients and healthcare professionals alike.
    </p>

    <section>
        <h3 onclick="toggleDropdown(this)">Our Mission</h3>
        <div class="dropdown-content">
            <!-- Add the "show" class to make it the default -->
            <p>
                Our mission is simple yet profound: to offer accurate, detailed, and compassionate MRI imaging services that empower
                patients and healthcare providers with the information they need to make informed decisions about their health.
                We believe in the power of medical imaging to transform healthcare, and we are passionate about delivering the highest
                quality care to every individual we serve.
            </p>
        </div>
    </section>

    <section>
        <h3 onclick="toggleDropdown(this)">Cutting-Edge MRI Technology</h3>
        <div class="dropdown-content">
            <p>
                We understand that medical imaging plays a pivotal role in diagnosis and treatment planning. That's why we invest in
                the latest MRI technology, ensuring that our patients receive the most precise and comprehensive imaging available.
                Our state-of-the-art MRI scanners are designed to capture detailed images of the body's internal structures, helping
                healthcare professionals detect and evaluate a wide range of medical conditions.
            </p>
        </div>
    </section>

    <section>
        <h3 onclick="toggleDropdown(this)">Expertise and Compassion</h3>
        <div class="dropdown-content">
            <p>
                At VMed, we are more than just a medical imaging facility – we are a team of dedicated professionals who care deeply
                about our patients. Our experienced radiologists and technologists are committed to providing a comfortable and
                reassuring experience during your MRI procedure. We understand that undergoing medical imaging can be an anxious
                time, and we are here to answer your questions and address your concerns with empathy and expertise.
            </p>
        </div>
    </section>

    <section>
        <h3 onclick="toggleDropdown(this)">Patient-Centered Care</h3>
        <div class="dropdown-content">
            <p>
                We place our patients at the center of everything we do. From the moment you schedule your MRI appointment to the
                delivery of your results, our focus is on your well-being. Our friendly and knowledgeable staff will guide you
                through the process, ensuring that you feel informed and supported every step of the way.
            </p>
        </div>
    </section>

    <section>
        <h3 onclick="toggleDropdown(this)">Collaborative Healthcare</h3>
        <div class="dropdown-content">
            <p>
                VMed Medical Imaging Group collaborates closely with referring physicians and healthcare providers to ensure that
                the MRI imaging we provide is integrated seamlessly into your overall healthcare plan. We believe in the importance
                of a collaborative approach to healthcare, and we provide timely, accurate reports to your healthcare team to
                facilitate diagnosis and treatment.
            </p>
        </div>
    </section>
</main>

<script>
    function toggleDropdown(element) {
        var content = element.nextElementSibling;
        if (content.style.display === "block") {
            content.style.display = "none";
            element.querySelector('::after').style.transform = 'rotate(0deg)';
        } else {
            content.style.display = "block";
            element.querySelector('::after').style.transform = 'rotate(180deg)';
        }
    }
</script>

FIT5032_VMedProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title - Vincent</h2>

    <address>
        800 Swanston Street<br />
        Carlton, VIC 3053<br />
        <abbr title="Phone">P:</abbr>
        0466598833
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:vinc0003@student.monash.edu">vinc0003@student.monash.edu</a><br />
    </address>
</main>

FIT5032_VMedProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "VMed MRI Imaging Group";
}

<style>
    .btn-dark-blue {
        background-color: #0000A0; /* Dark blue color (adjust as needed) */
        color: #FFFFFF; /* Text color (usually white on a dark background) */
        border-color: #0000A0; /* Border color */
    }

        .btn-dark-blue:hover {
            background-color: #00008B; /* Dark blue color on hover (adjust as needed) */
            border-color: #00008B; /* Border color on hover */
        }

    /* Style for the full-width banner container */
    .full-width-banner-container {
        position: relative; /* Set the container to a relative position */
    }

    /* Style for the full-width banner image */
    .full-width-banner {
        width: 100%; /* Make the banner fill the entire width */
        height: 450px; /* Set the height to 500 pixels */
        display: block;
        max-width: 100%; /* Ensure the image doesn't exceed its natural size */
    }

    /* Style for the button overlay "Book Appointment" */
    .button-overlay {
        position: absolute; /* Set the button to an absolute position */
        top: 90%; /* Adjust the vertical position as needed */
        right: 17%; /* Adjust the horizontal position as needed */
        text-align: center;
        transform: translateY(-50%); /* Center the button vertically */
    }

    /* Style for the button overlay "Location" */
    .button-overlay1 {
        position: absolute; /* Set the button to an absolute position */
        top: 90%; /* Adjust the vertical position as needed */
        right: 5%; /* Adjust the horizontal position as needed */
        text-align: center;
        transform: translateY(-50%); /* Center the button vertically */
    }

    /* Style for the text overlay (initially hidden) */
    .text-overlay {
        position: absolute; /* Set the text to an absolute position */
        top: 40%; /* Adjust the vertical position as needed */
        left: 50%; /* Center the text horizontally */
        transform: translateX(-50%); /* Center the text horizontally */
        text-align: center;
        color: #FFFFFF; /* Text color (adjust as needed) */
        background: rgba(0, 0, 0, 0.5); /* Semi-transparent background for readability */
        padding: 10px;
        max-width: 90%; /* Limit the text width */
        font-size: 15px;
        opacity: 0; /* Initially hidden */
        transition: opacity 0.3s ease-in-out; /* Add a smooth transition for opacity */
    }

    /* Style for the text overlay when hovered */
    .full-width-banner-container:hover .text-overlay {
        opacity: 1; /* Show the text when the container is hovered */
    }
</style>

<main>
    <!-- Full-width banner section -->
    <section class="full-width-banner-container">
        <!-- Image with a responsive class -->
        <img class="full-width-banner" src="@Url.Content("~/Content/Images/banner_1280px.jpg")" alt="MRI Image" />
        <!-- "Book Appointment" button as an overlay -->
        <div class="button-overlay">
            <a class="btn btn-primary btn-lg btn-dark-blue" href="@Url.Action("Index", "Appointments", new { area = "" })">Book Appointment &raquo;</a>
        </div>
        <!-- "Location" button as an overlay -->
        <div class="button-overlay1">
            <a class="btn btn-primary btn-lg btn-dark-blue" href="@Url.Action("Index", "Clinics", new { area = "" })">Location &raquo;</a>
        </div>
        <!-- Text overlay (initially hidden) -->
        <div class="text-overlay">
            <p>We're open and welcoming patients</p>
            <br />
            <p>VMed MRI Imaging Group facilities located throughout Victoria, Western Australia, and South Australia - We are dedicated to supporting your medical imaging needs.</p>
        </div>
    </section>

    <div class="row">
        <div class="col-md-4">
            <section aria-labelledby="doctorsTitle">
                <h2 id="doctorsTitle">Our Doctors</h2>
                <p>
                    VMed MRI Imaging Group is dedicated to providing high-quality MRI imaging services for healthcare professionals and patients.
                </p>
                <p><a class="btn btn-primary btn-md" href="@Url.Action("Index", "Doctors", new { area = "" })">Learn more &raquo;</a></p>
            </section>
        </div>
        <div class="col-md-4">
            <section aria-labelledby="servicesTitle">
                <h2 id="servicesTitle">Our Services</h2>
                <p>Discover our wide range of MRI imaging services, including advanced diagnostic imaging and expert radiology consultations.</p>
                <p><a class="btn btn-primary btn-md" href="@Url.Action("Index", "Services", new { area = "" })">Learn more &raquo;</a></p>
            </section>
        </div>
        <div class="col-md-4">
            <section aria-labelledby="contactTitle">
                <h2 id="contactTitle">Contact Us</h2>
                <p>Contact us today to schedule an appointment or inquire about our imaging solutions and services.</p>
                <br />
                <p><a class="btn btn-primary btn-md" href="@Url.Action("Contact", "Home", new { area = "" })">Contact &raquo;</a></p>
            </section>
        </div>
    </div>
</main>